# Motion Detection Configuration

# Basic motion detection parameters
threshold_value: 40         # Pixel intensity difference threshold (increased for less noise)
min_contour_area: 2000     # Minimum area (in pixels) to reduce multiple detections

# Trajectory tracking parameters
max_tracking_distance: 100  # Maximum pixel distance (reduced to prevent jumping between objects)
max_trajectory_points: 30   # Reduced trail length for cleaner visualization

# Display parameters
max_threshold: 255         # Maximum value for binary threshold operation

# Motion smoothing parameters
smoothing_factor: 0.6      # Higher value = more smoothing (0.0 to 1.0)
min_tracking_confidence: 0.8  # Minimum confidence to maintain tracking

# Image Processing Techniques (enable/disable individual techniques)
enable_gaussian_blur: true     # Reduce noise with Gaussian blur
gaussian_blur_size: 5          # Size of Gaussian blur kernel (odd number)

enable_morphology: true        # Enable morphological operations
morphology_kernel_size: 5      # Size of morphological operation kernel (odd number)
enable_morph_close: true       # Close operation to fill gaps within objects
enable_morph_open: true        # Open operation to remove small noise
enable_dilation: true          # Additional dilation to make objects more cohesive
enable_erosion: false          # Erosion to reduce object size (use with caution)

enable_contrast_enhancement: false  # Enhance contrast using CLAHE
clahe_clip_limit: 2.0         # CLAHE clip limit for contrast enhancement
clahe_tile_size: 8            # CLAHE tile size

enable_median_blur: false     # Alternative blur method (good for salt-and-pepper noise)
median_blur_size: 5           # Size of median blur kernel (odd number)

enable_bilateral_filter: false # Edge-preserving smoothing
bilateral_d: 15               # Bilateral filter diameter
bilateral_sigma_color: 75     # Bilateral filter sigma color
bilateral_sigma_space: 75     # Bilateral filter sigma space

enable_adaptive_threshold: false  # Use adaptive thresholding instead of simple threshold
adaptive_block_size: 11       # Block size for adaptive threshold
adaptive_c: 2                 # Constant subtracted from mean

# Background Subtraction (MOG2)
enable_background_subtraction: true  # Use MOG2 background subtractor
background_history: 500       # Number of frames for background model
background_threshold: 16      # Threshold for background subtraction
background_detect_shadows: true  # Detect shadows (slower but more accurate)

# Convex Hull Processing
enable_convex_hull: true      # Use convex hull to fill gaps in contours
convex_hull_fill: true        # Fill the convex hull area

# HSV Color Filtering (useful for skin detection, object tracking)
enable_hsv_filtering: false   # Enable HSV color filtering
hsv_lower_h: 0               # Lower bound for Hue (0-179)
hsv_lower_s: 30              # Lower bound for Saturation (0-255)
hsv_lower_v: 60              # Lower bound for Value (0-255)
hsv_upper_h: 20              # Upper bound for Hue (0-179)
hsv_upper_s: 150             # Upper bound for Saturation (0-255)
hsv_upper_v: 255             # Upper bound for Value (0-255)

# Additional Advanced Techniques
enable_edge_detection: false  # Use Canny edge detection
canny_low_threshold: 50       # Canny low threshold
canny_high_threshold: 150     # Canny high threshold

enable_contour_approximation: true  # Approximate contours to reduce noise
contour_epsilon_factor: 0.02   # Approximation accuracy (0.01-0.05)

enable_contour_filtering: true  # Filter contours by shape properties
min_aspect_ratio: 0.3         # Minimum width/height ratio
max_aspect_ratio: 3.0         # Maximum width/height ratio
min_solidity: 0.5             # Minimum contour solidity (area/convex_hull_area)

# Data Collection parameters
enable_data_collection: true           # Enable/disable data collection
cleanup_old_data: true                 # If true, deletes old data on startup. If false, preserves old data
image_format: "png"                    # Format for saving cropped images
save_interval_seconds: 5               # How often to save data to disk

# Visualization parameters
enable_split_screen: true              # Enable/disable split-screen visualization
split_screen_window_name: "Motion Detection - Split Screen View"  # Window title for split-screen view

# MongoDB Configuration
mongodb_uri: "mongodb://localhost:27017"  # MongoDB connection URI
database_name: "birds_of_play"           # Database name
collection_prefix: "motion_tracking"      # Prefix for collections (will create motion_tracking_data and motion_tracking_images)

# Add more parameters as needed 