# Motion Detection Configuration - Cleaned Version
# This config file contains only the variables that are actually used by the codebase

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging:
  log_level: "debug"              # Options: "trace", "debug", "info", "warn", "error", "critical", "off"
  log_to_file: true               # Enable logging to file
  log_file_path: "birdsofplay.log" # Path to log file

# ===============================
# IMAGE PROCESSING
# ===============================
processing_mode: "grayscale"      # Color processing mode: "grayscale", "hsv", "rgb", "ycrcb"

# Image Preprocessing
contrast_enhancement: true        # Apply CLAHE contrast enhancement
clahe_clip_limit: 3.0            # CLAHE clip limit (1.0-5.0, higher = more contrast)
clahe_tile_size: 8               # CLAHE tile size (4-16, must be even)

# Blur Parameters
gaussian_blur_size: 7            # Gaussian blur kernel size (3-15, odd numbers only)
median_blur_size: 5              # Median blur kernel size (3-15, odd numbers only)
bilateral_d: 15                  # Bilateral filter diameter (5-25)
bilateral_sigma_color: 75        # Bilateral filter sigma color (10-150)
bilateral_sigma_space: 75        # Bilateral filter sigma space (10-150)

# ===============================
# MOTION DETECTION
# ===============================
background_subtraction: true     # Enable background subtraction
max_threshold: 255               # Maximum threshold value

# ===============================
# MORPHOLOGICAL OPERATIONS
# ===============================
morphology: true                 # Enable morphological operations
morph_kernel_size: 7            # Kernel size for morphological operations (3-15, odd numbers)
morph_close: true               # Fill holes in objects
morph_open: true                # Remove noise blobs
dilation: true                  # Expand objects
erosion: false                  # Shrink objects

# ===============================
# CONTOUR PROCESSING
# ===============================
convex_hull: true               # Apply convex hull to contours
contour_approximation: true     # Simplify contour shapes
contour_epsilon_factor: 0.03    # Approximation accuracy (0.01-0.1, lower = more accurate)
contour_filtering: true         # Enable contour filtering

# Contour Filtering Parameters
min_contour_area: 200           # Minimum contour area to keep (100-2000)
max_contour_aspect_ratio: 3.0   # Maximum width/height ratio (1.5-5.0)
min_contour_solidity: 0.3       # Minimum solidity ratio (0.3-0.9)

# ===============================
# DATA COLLECTION
# ===============================
data_collection: true           # Enable data collection and saving
cleanup_old_data: true          # Delete old data on startup
image_format: "png"             # Format for saving images
min_tracking_confidence: 0.6    # Minimum confidence for tracking

# MongoDB Configuration
mongodb_uri: "mongodb://localhost:27017"
database_name: "birds_of_play"
collection_prefix: "motion_tracking"
