# Image Detection Configuration
# ============================

# Detection Model Configuration
model_type: "yolo"                     # Model type (yolo, rcnn, ssd, etc.)
detection_model: "yolo11n"             # Model name (yolo11n, yolo11s, yolo11m, yolo11l, yolo11x)
model_path: "yolo11n.pt"              # Path to model file (will download if not found)
confidence_threshold: 0.25            # Minimum confidence for detections (0.0-1.0)

# Processing Configuration
max_frames_to_process: 1000            # Maximum number of frames to process in one run
batch_size: 1                          # Number of frames to process in parallel (future enhancement)

# MongoDB Configuration
collection_name: "detection_results"   # MongoDB collection name for storing results
create_indexes: true                   # Whether to create database indexes

# Web Interface Configuration
web_port: 3001                         # Port for detection results web interface
web_host: "localhost"                  # Host for web interface

# Logging Configuration
log_level: "INFO"                      # Logging level (DEBUG, INFO, WARNING, ERROR)
log_to_file: false                     # Whether to log to file
log_file_path: "image_detection.log"   # Path to log file

# Performance Configuration
enable_gpu: true                       # Whether to use GPU acceleration (if available)
num_workers: 1                         # Number of worker threads for processing
