name: C++ Code Quality

on:
  push:
    branches: [ main ]
    paths:
      - 'motion_detection/**'
      - '.github/workflows/cpp-quality.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'motion_detection/**'
      - '.github/workflows/cpp-quality.yml'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck valgrind libopencv-dev

    # Temporarily disabled clang-tidy
    # - name: Run clang-tidy
    #   run: |
    #     cd motion_detection
    #     clang-tidy include/motion_tracker.hpp src/motion_tracker.cpp src/main.cpp -checks=*,-fuchsia-*,-google-*,-zircon-*,-abseil-*,-modernize-use-trailing-return-type -- -I/usr/include/opencv4

    - name: Run cppcheck
      run: |
        cd motion_detection
        cppcheck --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --error-exitcode=1 .

    - name: Run Valgrind
      run: |
        cd motion_detection
        mkdir build && cd build
        cmake ..
        make
        valgrind --leak-check=full --error-exitcode=1 ./BirdsOfPlay

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Birds of Play'
        path: '.'
        format: 'HTML'
        out: 'reports'

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2 