name: C++ Code Quality

on:
  push:
    paths:
      - 'motion_detection/**'
      - '.github/workflows/cpp-quality.yml'
  pull_request:
    paths:
      - 'motion_detection/**'
      - '.github/workflows/cpp-quality.yml'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          valgrind \
          libopencv-dev \
          libgtest-dev \
          libyaml-cpp-dev \
          cmake \
          libboost-all-dev \
          libssl-dev \
          pkg-config \
          curl \
          uuid-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib/

    - name: Install MongoDB C Driver
      run: |
        cd /tmp
        curl -LO https://github.com/mongodb/mongo-c-driver/releases/download/1.24.3/mongo-c-driver-1.24.3.tar.gz
        tar xzf mongo-c-driver-1.24.3.tar.gz
        cd mongo-c-driver-1.24.3
        mkdir -p cmake-build && cd cmake-build
        cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make -j$(nproc)
        sudo make install

    - name: Install MongoDB C++ Driver
      run: |
        cd /tmp
        curl -LO https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.0/mongo-cxx-driver-r3.8.0.tar.gz
        tar xzf mongo-cxx-driver-r3.8.0.tar.gz
        cd mongo-cxx-driver-r3.8.0
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Build and Run Tests
      run: |
        cd motion_detection
        mkdir -p build && cd build
        cmake -DCMAKE_PREFIX_PATH=/usr/local/lib/cmake ..
        make
        valgrind --leak-check=full \
          --show-leak-kinds=definite \
          --errors-for-leak-kinds=definite \
          --error-exitcode=1 \
          --gen-suppressions=all \
          ./motion_tracker_test

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libopencv-dev \
          libgtest-dev \
          libyaml-cpp-dev \
          cmake \
          libboost-all-dev \
          libssl-dev \
          pkg-config \
          curl \
          uuid-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib/

    - name: Install MongoDB C Driver
      run: |
        cd /tmp
        curl -LO https://github.com/mongodb/mongo-c-driver/releases/download/1.24.3/mongo-c-driver-1.24.3.tar.gz
        tar xzf mongo-c-driver-1.24.3.tar.gz
        cd mongo-c-driver-1.24.3
        mkdir -p cmake-build && cd cmake-build
        cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make -j$(nproc)
        sudo make install

    - name: Install MongoDB C++ Driver
      run: |
        cd /tmp
        curl -LO https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.0/mongo-cxx-driver-r3.8.0.tar.gz
        tar xzf mongo-cxx-driver-r3.8.0.tar.gz
        cd mongo-cxx-driver-r3.8.0
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Birds of Play'
        path: '.'
        format: 'HTML'
        out: 'reports'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
        build-mode: manual

    - name: Build for CodeQL
      run: |
        cd motion_detection
        mkdir -p build && cd build
        cmake -DCMAKE_PREFIX_PATH=/usr/local/lib/cmake ..
        make

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:cpp"
      continue-on-error: true
